# Generated by Django 2.2.24 on 2021-11-15 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Misure_PD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_sito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Sito')),
            ],
        ),
        migrations.CreateModel(
            name='Contatti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_sito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Sito')),
            ],
        ),
    ]
