# Generated by Django 2.2.24 on 2021-11-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sito',
            name='Localita',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
