# Generated by Django 2.2.24 on 2021-11-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20211115_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatti',
            name='Cognome',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='contatti',
            name='Email',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='contatti',
            name='Nome',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='contatti',
            name='Priorita',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='contatti',
            name='Ruolo',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='contatti',
            name='Telefono',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='misure_pd',
            name='Data_acquisizione',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='misure_pd',
            name='Lunghezza_stendimento',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='misure_pd',
            name='Note',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='misure_pd',
            name='caratteristiche_sito',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='misure_pd',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='misure_pd',
            name='spettro',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='misure_pd',
            name='vr40',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='misure_pd',
            name='vs30',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='sito',
            name='Indirizzo',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='sito',
            name='Link_earth',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='sito',
            name='Link_foto',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='sito',
            name='Link_scheda',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='sito',
            name='Localita',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='sito',
            name='Posizione_GPS',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='sito',
            name='Provincia',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='sito',
            name='Serial_n',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='sito',
            name='Status',
            field=models.TextField(default=None),
        ),
    ]
