# Generated by Django 2.2.24 on 2021-11-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211115_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatti',
            old_name='Cognome',
            new_name='cognome',
        ),
        migrations.RenameField(
            model_name='contatti',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contatti',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='contatti',
            old_name='Priorita',
            new_name='priorita',
        ),
        migrations.RenameField(
            model_name='contatti',
            old_name='Ruolo',
            new_name='ruolo',
        ),
        migrations.RenameField(
            model_name='contatti',
            old_name='Telefono',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='misure_pd',
            old_name='Data_acquisizione',
            new_name='data_acquisizione',
        ),
        migrations.RenameField(
            model_name='misure_pd',
            old_name='Lunghezza_stendimento',
            new_name='lunghezza_stendimento',
        ),
        migrations.RenameField(
            model_name='misure_pd',
            old_name='Note',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='sito',
            old_name='Indirizzo',
            new_name='indirizzo',
        ),
        migrations.RenameField(
            model_name='sito',
            old_name='Link_earth',
            new_name='link_earth',
        ),
        migrations.RenameField(
            model_name='sito',
            old_name='Link_foto',
            new_name='link_foto',
        ),
        migrations.RenameField(
            model_name='sito',
            old_name='Link_scheda',
            new_name='link_scheda',
        ),
        migrations.RenameField(
            model_name='sito',
            old_name='Localita',
            new_name='localita',
        ),
        migrations.RenameField(
            model_name='sito',
            old_name='Posizione_GPS',
            new_name='posizione_GPS',
        ),
        migrations.RenameField(
            model_name='sito',
            old_name='Provincia',
            new_name='provincia',
        ),
        migrations.RenameField(
            model_name='sito',
            old_name='Serial_n',
            new_name='serial_n',
        ),
        migrations.RenameField(
            model_name='sito',
            old_name='Status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='contatti',
            name='ID_sito',
        ),
        migrations.RemoveField(
            model_name='misure_pd',
            name='ID_sito',
        ),
    ]
